### ISSUE TITLE
Critical bug in imbl dependency

### ISSUE THREAD

**Issue by nullchinchilla** [mel-project/melstf#5]
Discovered through fuzzing. This is definitely an upstream bug in `imbl::Vector`, as `append` should *never* panic.

We should fuzz `imbl` individually to find a minimal test case.

```
thread 'main' panicked at 'Chunk::pop_front: can't pop from empty chunk', /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/sized-chunks-0.6.5/src/sized_chunk/mod.rs:399:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:541:12
   1: sized_chunks::sized_chunk::Chunk<A,N>::pop_front
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/sized-chunks-0.6.5/src/sized_chunk/mod.rs:399:13
   2: imbl::nodes::rrb::Size::pop
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/nodes/rrb.rs:110:37
   3: imbl::nodes::rrb::Size::pop
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/nodes/rrb.rs:126:9
   4: imbl::nodes::rrb::Node<A>::push_chunk
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/nodes/rrb.rs:610:25
   5: imbl::nodes::rrb::Node<A>::push_chunk
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/nodes/rrb.rs:646:23
   6: imbl::vector::RRB<A>::push_middle
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/vector/mod.rs:1637:19
   7: imbl::vector::Vector<A>::append
             at /home/miyuruasuka/.cargo/registry/src/github.com-1ecc6299db9ec823/imbl-1.0.1/./src/vector/mod.rs:1053:21
   8: themelio_stf::melvm::Executor::step::{{closure}}::{{closure}}
             at ./src/melvm.rs:505:21
   9: themelio_stf::melvm::Executor::do_binop
             at ./src/melvm.rs:256:20
  10: themelio_stf::melvm::Executor::step::{{closure}}
             at ./src/melvm.rs:501:36
  11: themelio_stf::melvm::Executor::step
             at ./src/melvm.rs:591:19
  12: themelio_stf::melvm::Executor::run_to_end
             at ./src/melvm.rs:293:16
  13: themelio_stf::melvm::Covenant::check_raw
             at ./src/melvm.rs:109:13
```

**Comment by nullchinchilla** [comment]
We no longer depend on imbl at all.
